// src/components/Navbar/Header.jsx
import React from 'react'

function Header() {
    return (
        <div>
            {/* Nabbar goes here */}

            <nav className="bg-grey-400 text-white ">

                <div className="max-w-7xl border border-red-400">
                    {/* <div className="px-8 border mx-auto border-red-400"> */}

                    {/* <div className="flex justify-center"> */}
                    <div className="flex justify-between">
                        {/* <div className="flex justify-around"> */}

                        {/* primary nav */}
                        <div className="flex items-center space-x-3">
                            <a className="py-5 px-3  text-gray-700" href="">Features</a>
                            <a className="py-5 px-3 text-gray-700" href="">Pricing</a>
                        </div>

                        {/* logo */}
                        <div className="flex space-x-4 hover:bg-purple-200">
                            <div>
                                <a href="" className="flex items-center py-5 px-3 text-gray-700">
                                    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                                    </svg>
                                    <span className="font-bold">Better dev</span>
                                </a>
                            </div>
                            {/* primary nav
                            <div className="flex items-center space-x-3">
                                <a className="py-5 px-3  text-gray-700" href="">Features</a>
                                <a className="py-5 px-3 text-gray-700" href="">Pricing</a>
                            </div> */}
                        </div>
                        {/* secondary nav  */}
                        <div className="flex items-center space-x-1">
                            <a href="" className="py-5 px-3  text-green-700 ">Login</a>
                            <a href="" className="py-5 px-3 bg-yellow-400 text-yellow-900 hover:bg-yellow-300 hover:text-yellow-800 rounded transition duration-300 ">Sign Up</a>
                        </div>

                    </div>
                </div>

            </nav>
            {/* mobile menu */}


            {/* content goes here */}

            <div className="py-32 text-center">
                <h2 className="font-extrabold text-6xl">Nabars Tailwind</h2>
            </div>
        </div>
    )
}

export default Header

// components/Header.vue
<template>
 <header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <nav class="flex lg:w-2/5 flex-wrap items-center text-base md:ml-auto">
      <a class="mr-5 hover:text-gray-900">First Link</a>
      <a class="mr-5 hover:text-gray-900">Second Link</a>
      <a class="mr-5 hover:text-gray-900">Third Link</a>
      <a class="hover:text-gray-900">Fourth Link</a>
    </nav>
    <a class="flex order-first lg:order-none lg:w-1/5 title-font font-medium items-center text-gray-900 lg:items-center lg:justify-center mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">Tailblocks</span>
    </a>
    <div class="lg:w-2/5 inline-flex lg:justify-end ml-5 lg:ml-0">
      <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Button
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </button>
    </div>
  </div>
</header>
</template>

<script>
export default {}
</script>clear
