// components/Header.vue
<template>
  <header>
    <div class="m-auto px-6 max-w-screen-xl bg-gray-400">
      <!-- navbar -->
      <Navbar />
      <!-- banner -->
      <Banner />
    </div>
  </header>
</template>

<script>
import Navbar from '../components/Navbar'
import Banner from '../components/Banner'

export default {
  components: {
    Navbar,
    Banner,
  },
}
</script>

// src/Pages/Header.jsx
import React from 'react'
import Banner from '../Components/Banner'
import HeaderTop from '../Components/HeaderTop'
import MiddlePara from '../Components/MiddlePara'
  import Product from '../Components/Product'
import Navbar from './Navbar'

function Header() {
    return (
        <div>
            <header className="py-4 shadow-sm bg-white">
                <HeaderTop />
            </header>
           <Banner />
           <Product />
           <MiddlePara />
           </div>
    )
}

export default Header
